version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "develop"
    versioning-strategy: lockfile-only
    assignees:
      - "NamNguyen99"
